USE db_car_company_ex;

CREATE TABLE `Company Title` (
    `COMPANY_PK` VARCHAR(20) NOT NULL,
    `COMPANY_NAME` VARCHAR(20) NULL,
    PRIMARY KEY (`COMPANY_PK`)
);

CREATE TABLE `CarInfo` (
    `CAR_PK` VARCHAR(20) NOT NULL,
    `COMPANY_NAME` VARCHAR(20) NOT NULL,
    `YEAR` VARCHAR(20) NULL,
    `CAR_NAME` VARCHAR(20) NULL,
    PRIMARY KEY (`CAR_PK`, `COMPANY_NAME`),
    UNIQUE (`COMPANY_NAME`)
);

CREATE TABLE `Car Option` (
    `OPTION_PK` VARCHAR(20) NOT NULL,
    `CAR_FK` VARCHAR(20) NOT NULL,
    `COMPANY_FK` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`OPTION_PK`, `CAR_FK`, `COMPANY_FK`),
    FOREIGN KEY (`CAR_FK`) REFERENCES `CarInfo` (`CAR_PK`),
    FOREIGN KEY (`COMPANY_FK`) REFERENCES `CarInfo` (`COMPANY_NAME`)
);

ALTER TABLE `CarInfo` ADD CONSTRAINT `FK_Company Title_TO_CarInfo_1` FOREIGN KEY (`COMPANY_NAME`) REFERENCES `Company Title` (`COMPANY_PK`);
