USE db_car_company_wonchul;

select CP_NAME as '회사이름', CAR_NAME as '자동차이름', DATE_YEAR as '연식', COUNT(`OPTION`) as '옵션 갯수' from CAR_INFO CI
INNER JOIN CAR_INFO_OPTIONS COP ON CI.CI_PK = COP.CI_FK
INNER JOIN COMPANY CP ON CP.CP_PK = CI.CP_FK
INNER JOIN CAR_NAME CN ON CN.CN_PK = CI.CN_FK
INNER JOIN MODEL_YEAR MY ON MY.YEAR_PK = CI.YEAR_FK
INNER JOIN OPTIONS OP ON OP.OP_PK = COP.OP_FK
GROUP BY CP.CP_PK, CN.CN_PK, MY.YEAR_PK, CI.CI_PK;

select CP_NAME as '회사이름', CAR_NAME as '자동차이름', DATE_YEAR as '연식', COUNT(`OPTION`) as '옵션 갯수' from CAR_INFO CI
INNER JOIN CAR_INFO_OPTIONS COP ON CI.CI_PK = COP.CI_FK
INNER JOIN COMPANY CP ON CP.CP_PK = CI.CP_FK
INNER JOIN CAR_NAME CN ON CN.CN_PK = CI.CN_FK
INNER JOIN MODEL_YEAR MY ON MY.YEAR_PK = CI.YEAR_FK
INNER JOIN OPTIONS OP ON OP.OP_PK = COP.OP_FK
GROUP BY CP.CP_PK, CN.CN_PK, MY.YEAR_PK, CI.CI_PK 
HAVING MY.DATE_YEAR = '2019';
-- HAVING 절을 마지막에 쓰는건 좋은방법이 아니다?

-- 쿼리문은 레코드를 줄이는게 가장 중요하다
-- 조인했을 때 가장 레코드가 적은것과 하는것이 좋고, 가장 데이터가 큰 것이 LEFT JOIN 으로 하는것이 좋다
SELECT * FROM CAR_INFO;

-- select CP_NAME as '회사이름', CAR_NAME as '자동차이름', DATE_YEAR as '연식', COUNT(`OPTION`) as '옵션 갯수'
-- FROM (SELECT * FROM CAR_INFO) CI 
-- GROUP BY CP.CP_PK, CN.CN_PK, MY.YEAR_PK, CI.CI_PK;