USE study_car_company_kiye;

-- select CP_NAME as '회사이름', CAR_NAME as '자동차이름', DATE_YEAR as '연식', COUNT(`OPTION`) as '옵션 갯수' from CAR_INFO CI
-- INNER JOIN CAR_INFO_OPTIONS COP ON CI.CI_PK = COP.CI_FK
-- INNER JOIN COMPANY CP ON CP.CP_PK = CI.CP_FK
-- INNER JOIN CAR_NAME CN ON CN.CN_PK = CI.CN_FK
-- INNER JOIN MODEL_YEAR MY ON MY.YEAR_PK = CI.YEAR_FK
-- INNER JOIN OPTIONS OP ON OP.OP_PK = COP.OP_FK
-- GROUP BY CP.CP_PK, CN.CN_PK, MY.YEAR_PK, CI.CI_PK;

SELECT 
    CP.CP_NAME AS '회사이름', 
    CN.CAR_NAME AS '자동차이름', 
    MY.DATE_YEAR AS '연식', 
    (SELECT COUNT(*) 
     FROM CAR_INFO_OPTIONS CO 
     WHERE CO.CI_FK = CI.CI_PK) AS '옵션 갯수'
FROM 
    CAR_INFO CI
INNER JOIN 
    COMPANY CP ON CP.CP_PK = CI.CP_FK
INNER JOIN 
    CAR_NAME CN ON CN.CN_PK = CI.CN_FK
INNER JOIN 
    MODEL_YEAR MY ON MY.YEAR_PK = CI.YEAR_FK
ORDER BY 
    CP.CP_NAME, CN.CAR_NAME, MY.DATE_YEAR;
