USE study_notice_kiye;

CREATE TABLE `NOTICE` (
	`Notice_PK`	VARCHAR(20)	NOT NULL,
	`WRITER_FK`	VARCHAR(20)	NOT NULL,
	`CONTENT`	VARCHAR(300)	NULL
);

CREATE TABLE `VISITORS` (
	`VISITOR_PK`	VARCHAR(20)	NOT NULL,
	`NOTICE_FK`	VARCHAR(20)	NOT NULL,
	`VISITOR_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `WRITERS` (
	`WRITER_PK`	VARCHAR(20)	NOT NULL,
	`Field`	VARCHAR(20)	NULL
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`Notice_PK`,
	`WRITER_FK`
);

ALTER TABLE `VISITORS` ADD CONSTRAINT `PK_VISITORS` PRIMARY KEY (
	`VISITOR_PK`,
	`NOTICE_FK`
);

ALTER TABLE `WRITERS` ADD CONSTRAINT `PK_WRITERS` PRIMARY KEY (
	`WRITER_PK`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_WRITERS_TO_NOTICE_1` FOREIGN KEY (
	`WRITER_FK`
)
REFERENCES `WRITERS` (
	`WRITER_PK`
);

ALTER TABLE `VISITORS` ADD CONSTRAINT `FK_NOTICE_TO_VISITORS_1` FOREIGN KEY (
	`NOTICE_FK`
)
REFERENCES `NOTICE` (
	`Notice_PK`
);

