USE db_car_company_NtoN_ex;

CREATE TABLE `CAR_INFORMATION_PK` (
	`CAR_INFORMATION_PK`	VARCHAR(20)	NOT NULL,
	`회사이름`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_NAME` (
	`CAR_NAME_PK`	VARCHAR(20)	NOT NULL,
	`Field`	VARCHAR(20)	NULL
);

CREATE TABLE `YEARS` (
	`YEAR_PK`	VARCHAR(20)	NOT NULL,
	`연식`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_INFONAME_YEAR` (
	`CAR_INFO_YEAR_PK`	VARCHAR(20)	NOT NULL,
	`CAR_INFORMATION_FK`	VARCHAR(20)	NOT NULL,
	`YEAR_FK`	VARCHAR(20)	NOT NULL,
	`CAR_NAME_FK`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `OPTIONS` (
	`OPTIONS_PK`	VARCHAR(20)	NOT NULL,
	`옵션`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_INFO_YEAR_OPTION` (
	`CI_YEAR_OPT_01`	VARCHAR(20)	NOT NULL,
	`CAR_INFO_YEAR_FK`	VARCHAR(20)	NOT NULL,
	`OPTIONS_PK`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `CAR_INFORMATION_PK` ADD CONSTRAINT `PK_CAR_INFORMATION_PK` PRIMARY KEY (
	`CAR_INFORMATION_PK`
);

ALTER TABLE `CAR_NAME` ADD CONSTRAINT `PK_CAR_NAME` PRIMARY KEY (
	`CAR_NAME_PK`
);

ALTER TABLE `YEARS` ADD CONSTRAINT `PK_YEARS` PRIMARY KEY (
	`YEAR_PK`
);

ALTER TABLE `CAR_INFONAME_YEAR` ADD CONSTRAINT `PK_CAR_INFONAME_YEAR` PRIMARY KEY (
	`CAR_INFO_YEAR_PK`,
	`CAR_INFORMATION_FK`,
	`YEAR_FK`,
	`CAR_NAME_FK`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `PK_OPTIONS` PRIMARY KEY (
	`OPTIONS_PK`
);

ALTER TABLE `CAR_INFO_YEAR_OPTION` ADD CONSTRAINT `PK_CAR_INFO_YEAR_OPTION` PRIMARY KEY (
	`CI_YEAR_OPT_01`,
	`CAR_INFO_YEAR_FK`,
	`OPTIONS_PK`
);

ALTER TABLE `CAR_INFONAME_YEAR` ADD CONSTRAINT `FK_CAR_INFORMATION_PK_TO_CAR_INFONAME_YEAR_1` FOREIGN KEY (
	`CAR_INFORMATION_FK`
)
REFERENCES `CAR_INFORMATION_PK` (
	`CAR_INFORMATION_PK`
);

ALTER TABLE `CAR_INFONAME_YEAR` ADD CONSTRAINT `FK_YEARS_TO_CAR_INFONAME_YEAR_1` FOREIGN KEY (
	`YEAR_FK`
)
REFERENCES `YEARS` (
	`YEAR_PK`
);

ALTER TABLE `CAR_INFONAME_YEAR` ADD CONSTRAINT `FK_CAR_NAME_TO_CAR_INFONAME_YEAR_1` FOREIGN KEY (
	`CAR_NAME_FK`
)
REFERENCES `CAR_NAME` (
	`CAR_NAME_PK`
);

ALTER TABLE `CAR_INFO_YEAR_OPTION` ADD CONSTRAINT `FK_CAR_INFONAME_YEAR_TO_CAR_INFO_YEAR_OPTION_1` FOREIGN KEY (
	`CAR_INFO_YEAR_FK`
)
REFERENCES `CAR_INFONAME_YEAR` (
	`CAR_INFO_YEAR_PK`
);

ALTER TABLE `CAR_INFO_YEAR_OPTION` ADD CONSTRAINT `FK_OPTIONS_TO_CAR_INFO_YEAR_OPTION_1` FOREIGN KEY (
	`OPTIONS_PK`
)
REFERENCES `OPTIONS` (
	`OPTIONS_PK`
);

